### ISSUE TITLE
Create database

### ISSUE THREAD

**Issue by clee11-uwg** [clee11-uwg/RecipeBookApp#4]
Create actual database tables in MySQL based on the ERD

**Comment by jm16731** [comment]
It's not so much creating the database as it is packaging it into our executable file, and/or uploading it to the web so that our executable can reference it. Dunno what to do with it for now.

**Comment by clee11-uwg** [comment]
the scope of this issue has been completed. I have created another issue that has Greg researching how to include the DB into the executable file
