### ISSUE TITLE
Change pswword

### ISSUE THREAD

**Issue by byadav1** [clee11-uwg/RecipeBookApp#97]
I see this in Change password, what if user don't knw the old password.. he will never be able to change his password

       oldPassword = Crypt.SHA256_hash(oldPassword);
                string logInPassword = this.UserDAL.VerifyUser(user.Name);
                
                if (!string.Equals(logInPassword, oldPassword, StringComparison.OrdinalIgnoreCase))
                {
                    throw new UnauthorizedAccessException("Incorrect password");
                }

**Comment by jm16731** [comment]
User shouldn't be able to change their password if they don't know it. Prevents accidental changes or malicious changes.
